config/routes.rb
Planet::Application.routes.draw do
  get "autocomplete/location"
  get "autocomplete/address"

  resources :categories

  resources :photos

  resources :categories, :path => "/adm/category/"

  resources :items do
    collection do
      get :search
    end
    member do
      get 'show_contact'
    end
  end

  resources :users
  
  controller :session do
  	get 'login' => :new
  	post 'login' => :create
  	get 'logout' => :destroy
  end

  get "home/index"
  
  root :to => "home#index"
  
  match "/i/:id" => "items#show"

end

app/models/item.rb
class Item < ActiveRecord::Base
  STEPS = %w[common description image]

  after_initialize :init
  before_save :set_represent_image

  belongs_to :user
  has_many :photos, :autosave => false, :dependent => :destroy, :foreign_key => :attachable_id
  has_one :category, :primary_key => :category_id, :foreign_key => :id
  has_one :represent, :class_name => 'Photo', :primary_key => :represent_image, :foreign_key => :id
  has_one :location, :class_name => 'Location', :primary_key => :location_id, :foreign_key => :id

  validates :title, :presence => true

  accepts_nested_attributes_for :photos, :allow_destroy => true
  code_field :shipping_method => 1

  # conditional indexing
  searchable :if => :confirmed do
    text :title, :as => :title_korean
    text :description, :as => :description_korean

    integer :price, :shipping_cost, :location_id
    integer :category_hierarchy, :multiple => true

    string :represent_image, :contact
    string :shipping_method
    string :location_si do
      location.try(:si)
    end
    time :created_at, :updated_at
    # Geospatial search is not implemented yet in sunspot 1.3.0
    # It will contain in version 2.0
    latlon(:location) { Sunspot::Util::Coordinates.new( location.latitude, location.longitude ) unless location.blank? }
  end

  # ActiveRecord::AssociatedAttributes 클래스는
  # update시 기본적으로 id, foreign_key를 조건으로 레코드를 찾는다.
  # 따라서 이번 경우와 같이 새로운 레코드가 추가될 경우에는 
  # 레코드를 찾을 수 없어 에러가 나므로 이 메서드를 추가해주었다.
  # TODO - 어뷰징 방지 로직을 넣자. 소유자 체크, 이미 등록된 사진인지 체크.
  def photos_attributes=(attributes)
    attributes.each do |key, attr|
      photos.push(Photo.find(attr['id']))
    end
  end

  def set_represent_image
    self.represent_image = photos.first.try(:id)
  end

  def category_hierarchy
    self.category.hierarchy.map { |c| c.id } unless self.category.blank?
  end

  def init
    self.step ||= steps.first
  end

  def current_step
    self.step
  end

  def steps
    STEPS
  end

  def next_step
    self.step = steps[steps.index(self.step)+1]
  end

  def previous_step
    self.step = steps[steps.index(self.step)-1]
  end

  def first_step?
    self.step == steps.first
  end

  def last_step?
    self.step == steps.last
  end

  def all_valid?
    steps.all? do |s|
      self.step = s
      valid?
    end
  end

end

app/controllers/items_controller.rb
# encoding: utf-8
class ItemsController < ApplicationController
	before_filter :authorize
	skip_before_filter :authorize, :only => [:index, :show, :search]

  # GET /items
  # GET /items.json
  def index
    @items = Item.order('created_at desc').page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new
  
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.valid?
        @item.next_step
        @item.save
        format.html { redirect_to edit_item_path(@item), notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])
    
    @item.attributes = params[:item]

    if params[:back_button]
      @item.previous_step
      @item.save
    elsif @item.valid?
      if @item.last_step?
        if @item.all_valid?
          @item.confirmed = true
          @item.save
          return respond_to do |format|    # last step && all vaild
            format.html { redirect_to @item, notice: 'Item was successfully updated.' }
            format.json { head :ok }
          end
        end
      else
        @item.next_step
      end
      @item.save
    end

    respond_to do |format|
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :ok }
    end
  end

  # GET /items/search
  # GET /items/search.xml
  def search
    # order
    if params[:order].blank?
      order_param = [:created_at, :desc]
    elsif params[:order] == 'location' && params[:current_location_id].present?
      cookies[:current_location_id] = { :value => params[:current_location_id], :expires => 15.days.from_now }
      cookies[:current_location_address] = { :value => Location.find(params[:current_location_id]).address, :expires => 15.days.from_now }
    else
      order_param = params[:order].split('_').collect { |s| s.to_sym }
      order_param[0] = :created_at if order_param[0] == :date
    end

    #search
    search = Item.search do
      keywords params[:query]

      all_of do
        with(:category_hierarchy, params[:category]) if params[:category].present?

        with(:created_at).greater_than(params[:period].to_i.days.ago) if params[:period].present?

        any_of do
          if params[:shipping_method] && params[:shipping_method].kind_of?(Array)
            params[:shipping_method].each do |p|
              with(:shipping_method, p)
            end
          end
        end
        any_of do
          if params[:location_si] && params[:location_si].kind_of?(Array)
            params[:location_si].each do |p|
              with(:location_si, p)
            end
          end
        end
      end

      if params[:order] == 'location' && params[:current_location_id].present?
        location_obj = Location.find(params[:current_location_id])
        order_by_geodist(:location, location_obj.latitude, location_obj.longitude)
      else
        order_by order_param[0], order_param[1]
      end
      facet :category_hierarchy

      paginate :page => params[:page], :per_page => 10
    end

    #result
    @items = search
    @facet = search.facet(:category_hierarchy).rows
    @category = Category.find(params[:category]) unless params[:category].blank?
    @info_categories = Category.find_all_by_facet(search.facet(:category_hierarchy).rows, params[:category])

    # below this line will be moved to widget
    @shipping_method_options = FieldValue.values_by_meta_id(1)
    @location_options = FieldValue.values_by_meta_id(2)
    @period_options = FieldValue.values_by_meta_id(3)

    respond_to do |format|
      format.html { render :action => "index" }
      format.xml { render :xml => @items }
    end
  end

  def show_contact
    @item = Item.find(params[:id])
    
    respond_to do |format|
      format.html { render :layout => false } # show_contact.html.erb whitout layout
      format.json { render json: @item.contact }
    end  
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def field_options( code, field_value = nil )
    FieldValue.where( :meta_id => code ).order( :seq )
  end

end

app/views/items/_left.html.erb
<div class="span3 left">
  <%= form_tag search_items_path, :method => :get do %>
    <%= hidden_field_tag :query, params[:query] %>
    <%= hidden_field_tag :category, params[:category] %>
    <%= hidden_field_tag :order, params[:order] %>
    <%= hidden_field_tag :current_location_id, params[:current_location_id] %>

    <%= render :partial => 'items/partial/left_categories' %>

    <div align="right">
      아래 조건으로
      <%= button_tag (content_tag(:i, '', :class => "icon-refresh icon-white") + " 다시 검색"), :type => 'submit', :class => 'btn btn-primary' %>
    </div>
    <hr>
    <h3>기간</h3>
    <ul class="filter_box well unstyled">
      <% @period_options.each do |i| %>
      <li><%= radio_button_tag 'period', i.value, params[:period] == i.value %><%= link_to i.name, url_for( self.params.merge(:period => i.value) ) %></li>
      <% end %>
    </ul>
    <hr>
    <h3><%= t "simple_form.labels.item.price" %></h3>
    <ul class="filter_box well unstyled">
      <li><%= check_box_tag :price, 10000, params[:price] %><%= link_to "~만원", url_for( self.params.merge(:price => 10000) ) %></li>
      <li><%= check_box_tag :price, 100000 %>만원 ~ 십만원</li>
      <li><%= check_box_tag :price, 1000000 %>십만원 ~ 백만원</li>
    </ul>
    <hr>
    <h3><%= t "simple_form.labels.item.shipping_method" %></h3>
    <ul class="filter_box well unstyled">
      <% @shipping_method_options.each do |l| %>
      <li><%= check_box_tag 'shipping_method[]', l.value, params[:shipping_method].try(:include?, l.value) %><%= link_to l.name, url_for( self.params.merge(:shipping_method => l.value) ) %></li>
      <% end %>
    </ul>
    <hr>
    <h3><%= t "simple_form.labels.item.location" %></h3>
    <ul class="filter_box well unstyled">
      <% @location_options.each do |l| %>
      <li><%= check_box_tag 'location_si[]', l.value, params[:location_si].try(:include?, l.value) %><%= link_to l.name, url_for( self.params.merge('location_si[]' => l.value) ) %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/items/edit.html.erb
<%= render "items/partial/form_#{@item.current_step}" %>

<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<style>
  /* order 박스 마진 */
  .order { margin: 0; }
  /* 왼쪽 검색 필터 스타일 */
  .filter_box { padding: 5px; }
  .filter_box input[type="checkbox"], .filter_box input[type="radio"] { margin-right: 5px; }
  /* 카테고리 breadcrumb */
  .left .breadcrumb { padding: 3px 7px; margin-bottom: 3px; }
  .left .categories { margin-left: 10px }
  .breadcrumb .label { text-shadow: 0 0px 0 white; }
</style>

<div class="row">
  <%= render :partial => 'left' %>
  
  <div class="span9">
    <%= render 'items/partial/search'%>
  
    <%= render 'items/partial/list'%>
  </div>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "items/partial/form_#{@item.current_step}" %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<style>
.item-thumbnails {}
</style>

<div>
  <h2><%= @item.title %></h2>
</div>
<hr />
<div class="row">
  <div class="span9">
    <div>
      <%= image_tag(@item.represent.data.url) if @item.represent %>
    </div>
    <ul class="item-thumbnails thumbnails">
      <% @item.photos.each do |p| %>
        <li><a href="#" class="thumbnail"><%= image_tag(p.data.url(:thumb)) %></a></li>
      <% end %>
    </ul>
  </div>
  <div class="span3">
    <h3>물품 정보</h3><hr />
    <%= show_for @item do |i| %>
    <%= i.attribute :price %>
      <%= i.association :location, :using => :address_sigu %>
      <%= i.attribute :shipping_method %>
      <%= i.attribute :shipping_cost %>
    <% end %>
    <br />
    <h3>판매자 정보</h3><hr />
    <%= show_for @item.user do |i| %>
      <%= i.attribute :name %>
      신용도
    <% end %>
    <div>
      <br /><hr />
      판매자 본인일 경우<br />
      <%= link_to edit_item_path(@item) , :class => 'btn btn-info' do %>
        <%= content_tag(:i, '', :class => "icon-pencil icon-white") %>
        물품수정
      <% end %>
      <%= link_to @item , confirm: '정말 삭제 하시겠습니까?', method: :delete, :class => 'btn btn-danger' do %>
        <%= content_tag(:i, '', :class => "icon-remove icon-white") %>
        물품삭제
      <% end %>
      <br><br>
      일반 사용자일 경우 <br />
      <%= link_to '#' , :class => 'btn btn-success' do %>
        <%= content_tag(:i, '', :class => "icon-envelope icon-white") %>
        구매신청
      <% end %>
      <%= button_tag :class => 'btn btn-info', :id => 'show_contact' do %>
        <%= content_tag(:i, '', :class => "icon-list-alt icon-white") %>
        연락처보기
      <% end %>
    </div>
  </div>
</div>
<hr />
<div>
  <%= @item.description %>
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>

<script>
  $(document).ready(function() {
    jItem.initAttachToMenu($('.item-thumbnails'));
    $('#show_contact').bind('click', function() {
      App.loadModal('<%= show_contact_item_path(@item) %>');      
    })
  });
</script>